server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-stacktrace: always
    include-exception: on
app:
  runCheck: false
  environment: localhost
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://postgresdb/postgres
    username: postgres 
    password: postgres
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 100
      minimum-idle: 20
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    drop-first: ${produ.drop.database:false}
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/create.sql
      hibernate:
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: false
    show-sql: false
    generate-ddl: on
    hibernate:
      ddl-auto: validate
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    use-code-as-default-message: false
    cache-duration: 10s
    fallback-to-system-locale: false
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 500
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 8h

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "metrics,info,health"
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.security: INFO
